spring:
  datasource:
    url: jdbc:teradata://10.12.152.240/DATABASE=LOAD_FND,TMODE=TERA,CHARSET=UTF8
    username: usr_load_fnd
    password: qodfs12W4Ds
    driver-class-name: com.teradata.jdbc.TeraDriver

app:
  database:
    schema: LOAD_FND
  auth:
    secret-key: lRC3aI4JnS7t0uCU
